import type { MobileGraphQLRequest } from "@rivonclaw/core";
import { API } from "@rivonclaw/core/api-contract";
import { executeMobileGraphQL } from "../../mobile/mobile-graphql.js";
import { getRpcClient } from "../../gateway/rpc-client-ref.js";
import { PAIRING_CODE_TTL_MS } from "../../store/mobile-manager.js";
import type { RouteRegistry, EndpointHandler } from "../route-registry.js";
import { parseBody, sendJson } from "../route-utils.js";

// ── POST /api/graphql/mobile ──

const mobileGraphql: EndpointHandler = async (req, res, _url, _params, ctx) => {
  const body = (await parseBody(req)) as MobileGraphQLRequest;
  const result = await executeMobileGraphQL(body, ctx);
  sendJson(res, 200, result);
};

// ── POST /api/mobile/pairing-code/generate ──

const pairingCode: EndpointHandler = async (_req, res, _url, _params, ctx) => {
  if (!ctx.mobileManager) {
    sendJson(res, 500, { error: "Mobile Manager not initialized" });
    return;
  }

  try {
    const codeData = await ctx.mobileManager.requestPairingCode();
    sendJson(res, 200, { ...codeData, ttlMs: PAIRING_CODE_TTL_MS });
  } catch (err: any) {
    sendJson(res, 500, { error: err.message || "Failed to generate pairing code" });
  }
};

// ── GET /api/mobile/install-url ──

const installUrl: EndpointHandler = async (_req, res, _url, _params, ctx) => {
  if (!ctx.mobileManager) {
    sendJson(res, 500, { error: "Mobile Manager not initialized" });
    return;
  }

  try {
    const result = await ctx.mobileManager.getInstallUrl();
    sendJson(res, 200, result);
  } catch (err: any) {
    sendJson(res, 500, { error: err.message || "Failed to get install URL" });
  }
};

// ── GET /api/mobile/status ──

const status: EndpointHandler = async (_req, res, _url, _params, ctx) => {
  if (!ctx.mobileManager) {
    sendJson(res, 500, { error: "Mobile Manager not initialized" });
    return;
  }

  const activeCode = ctx.mobileManager.getActiveCode();
  const pairings = ctx.mobileManager.root.mobilePairings.slice();

  // If a code generated by Desktop is awaiting mobile pairing, poll the Control Plane
  if (activeCode) {
    ctx.mobileManager
      .pollPairingStatus(activeCode.code)
      .then(
        (
          status: {
            paired: boolean;
            accessToken?: string;
            relayUrl?: string;
            pairingId?: string;
            desktopDeviceId?: string;
            mobileDeviceId?: string;
          } | null,
        ) => {
          if (status && status.paired && status.accessToken && status.relayUrl) {
            ctx.mobileManager!.completePairing(status as {
              accessToken: string;
              relayUrl: string;
              pairingId?: string;
              desktopDeviceId?: string;
              mobileDeviceId?: string;
            });
          }
        },
      )
      .catch((e: unknown) => console.error("Pairing wait failed", e));
  }

  sendJson(res, 200, {
    pairings,
    activeCode: activeCode || null,
    desktopDeviceId: ctx.mobileManager.getDesktopDeviceId(),
  });
};

// ── GET /api/mobile/device-status ──

const deviceStatus: EndpointHandler = async (_req, res, _url, _params, ctx) => {
  // Lazy migration: re-key old mobileDeviceId-based allowlist entries to pairingId
  if (ctx.mobileManager) {
    ctx.mobileManager.runMigration();
  }

  const rpcClient = getRpcClient();
  if (!rpcClient?.isConnected()) {
    sendJson(res, 200, { devices: {} });
    return;
  }

  try {
    const result = (await rpcClient.request("mobile_chat_device_status", {})) as {
      devices: Record<string, any>;
    };

    // Auto-persist stale status from plugin to DB
    const allPairings = ctx.mobileManager?.root.mobilePairings ?? [];
    for (const [pairingKey, status] of Object.entries(result.devices)) {
      if (status.stale) {
        const pairing = (allPairings as any[]).find(
          (p: any) => p.pairingId === pairingKey || p.id === pairingKey,
        );
        if (pairing && pairing.status !== "stale") {
          ctx.mobileManager?.markStale(pairing.id);
        }
      }
    }

    // Merge DB stale records (survives gateway restart)
    for (const p of allPairings as any[]) {
      const key = p.pairingId || p.id;
      if (p.status === "stale" && key && !result.devices[key]) {
        result.devices[key] = {
          relayConnected: false,
          mobileOnline: false,
          stale: true,
        };
      }
    }

    sendJson(res, 200, result);
  } catch (err: any) {
    // Even on RPC failure, return DB stale records
    const devices: Record<string, any> = {};
    try {
      const allPairings = ctx.mobileManager?.root.mobilePairings ?? [];
      for (const p of allPairings as any[]) {
        const key = p.pairingId || p.id;
        if (p.status === "stale" && key) {
          devices[key] = {
            relayConnected: false,
            mobileOnline: false,
            stale: true,
          };
        }
      }
    } catch {
      /* ignore */
    }
    sendJson(res, 200, { devices });
  }
};

// ── DELETE /api/mobile/disconnect ──

const disconnect: EndpointHandler = async (_req, res, url, _params, ctx) => {
  if (!ctx.mobileManager) {
    sendJson(res, 500, { error: "Mobile Manager not initialized" });
    return;
  }

  try {
    const pairingId = url.searchParams.get("pairingId") || undefined;
    if (pairingId) {
      ctx.mobileManager.removePairing(pairingId);
    } else {
      ctx.mobileManager.disconnectAll();
    }
    sendJson(res, 200, { success: true });
  } catch (err: any) {
    sendJson(res, 500, { error: err.message || "Failed to disconnect mobile pairing" });
  }
};

// ── Registration ──

export function registerMobileChatHandlers(registry: RouteRegistry): void {
  registry.register(API["mobile.graphql"], mobileGraphql);
  registry.register(API["mobile.pairingCode"], pairingCode);
  registry.register(API["mobile.installUrl"], installUrl);
  registry.register(API["mobile.status"], status);
  registry.register(API["mobile.deviceStatus"], deviceStatus);
  registry.register(API["mobile.disconnect"], disconnect);
}
